services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: stickit-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    container_name: stickit-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: stickit-frontend
    ports:
      - "19999:80"
    depends_on:
      - backend

volumes:
  db-data:
