# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: 3600
    token_extractors:
        authorization_header:
            enabled: true
            prefix: 'Bearer '
            name: Authorization
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER:
            lifetime: 0
            path: '/'
            domain: null
            secure: false   # false for local HTTP (use true in production for HTTPS)
            httpOnly: true
            samesite: lax
